In [12]:
import pandas as pd 
import numpy as np

data = {
    "StudentID": [201, 202, 203, 204, 205, 206, 207],
    "Name": ["Adam", "Mariam", "Yara", "Omar", "Salma", "Hady", "Nour"],
    "Course": [
        "Python",
        "Excel",
        "Power BI",
        "Python",
        "SQL",
        "Power BI",
        "Python",
    ],
    "Level": [
        "Beginner",
        "Beginner",
        "Inter",
        "Beginner",
        "Inter",
        "Inter",
        "Advanced",
    ],
    "City": ["Cairo", "Giza", "Alex", "Cairo", "Mansoura", "Alex", "Cairo"],
    "EnrollDate": pd.to_datetime([
        "2024-02-01",
        "2024-02-03",
        "2024-02-04",
        "2024-02-06",
        "2024-02-07",
        "2024-02-10",
        "2024-02-11",
    ]),
    "Done": ["Yes", "No", "Yes", "Yes", "No", "Yes", "Yes"],
    "Hours": [18, 7, 15, 20, 9, 14, 24],
    "Score": [88, 54, 91, 95, 61, 84, 90],
    "Rating": [4.8, np.nan, 4.9, 5.0, 3.8, 4.5, 4.7],  # np.nan لقيمة Missing
    "Price": [120, 80, 150, 120, 100, 150, 180],
}

df = pd.DataFrame(data)

01.  Preview the dataset and describe the numeric learning 
columns.
02.  Check data types, especially EnrollDate and Completed.
03.  Select StudentName, Course, HoursSpent, Score, and 
Rating.
04.  Filter completed students only.
05.  Filter students who scored 85 or more and spent at least 15 
hours

In [13]:
df.head(3)

,StudentID,Name,Course,Level,City,EnrollDate,Done,Hours,Score,Rating,Price
0,201,Adam,Python,Beginner,Cairo,2024-02-01,Yes,18,88,4.8,120
1,202,Mariam,Excel,Beginner,Giza,2024-02-03,No,7,54,NaN,80
2,203,Yara,Power BI,Inter,Alex,2024-02-04,Yes,15,91,4.9,150

In [14]:
df.tail(3)

,StudentID,Name,Course,Level,City,EnrollDate,Done,Hours,Score,Rating,Price
4,205,Salma,SQL,Inter,Mansoura,2024-02-07,No,9,61,3.8,100
5,206,Hady,Power BI,Inter,Alex,2024-02-10,Yes,14,84,4.5,150
6,207,Nour,Python,Advanced,Cairo,2024-02-11,Yes,24,90,4.7,180

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   7 non-null      int64
 1   Name        7 non-null      str
 2   Course      7 non-null      str
 3   Level       7 non-null      str
 4   City        7 non-null      str
 5   EnrollDate  7 non-null      datetime64[us]
 6   Done        7 non-null      str
 7   Hours       7 non-null      int64
 8   Score       7 non-null      int64
 9   Rating      6 non-null      float64
 10  Price       7 non-null      int64
dtypes: datetime64[us](1), float64(1), int64(4), str(5)
memory usage: 922.0 bytes

In [16]:
df.describe()

,StudentID,EnrollDate,Hours,Score,Rating,Price
count,7.000000,7,7.000000,7.000000,6.000000,7.000000
mean,204.000000,2024-02-06 00:00:00,15.285714,80.428571,4.616667,128.571429
min,201.000000,2024-02-01 00:00:00,7.000000,54.000000,3.800000,80.000000
25%,202.500000,2024-02-03 12:00:00,11.500000,72.500000,4.550000,110.000000
50%,204.000000,2024-02-06 00:00:00,15.000000,88.000000,4.750000,120.000000
75%,205.500000,2024-02-08 12:00:00,19.000000,90.500000,4.875000,150.000000
max,207.000000,2024-02-11 00:00:00,24.000000,95.000000,5.000000,180.000000
std,2.160247,NaN,5.992058,16.133373,0.435507,33.876526

In [17]:
df.shape

(7, 11)

In [18]:
selected_cols = ['Name','Course','Hours','Score','Rating']

df[selected_cols].head()

     Name    Course  Hours  Score  Rating
0    Adam    Python     18     88     4.8
1  Mariam     Excel      7     54     NaN
2    Yara  Power BI     15     91     4.9
3    Omar    Python     20     95     5.0
4   Salma       SQL      9     61     3.8

In [19]:
filter_students = df[df['Done']=='Yes']
filter_students

,StudentID,Name,Course,Level,City,EnrollDate,Done,Hours,Score,Rating,Price
0,201,Adam,Python,Beginner,Cairo,2024-02-01,Yes,18,88,4.8,120
2,203,Yara,Power BI,Inter,Alex,2024-02-04,Yes,15,91,4.9,150
3,204,Omar,Python,Beginner,Cairo,2024-02-06,Yes,20,95,5.0,120
5,206,Hady,Power BI,Inter,Alex,2024-02-10,Yes,14,84,4.5,150
6,207,Nour,Python,Advanced,Cairo,2024-02-11,Yes,24,90,4.7,180

In [20]:
filter_students_scored = df[(df['Score'] > 85)&(df['Hours'] >= 15)]
filter_students_scored

,StudentID,Name,Course,Level,City,EnrollDate,Done,Hours,Score,Rating,Price
0,201,Adam,Python,Beginner,Cairo,2024-02-01,Yes,18,88,4.8,120
2,203,Yara,Power BI,Inter,Alex,2024-02-04,Yes,15,91,4.9,150
3,204,Omar,Python,Beginner,Cairo,2024-02-06,Yes,20,95,5.0,120
6,207,Nour,Python,Advanced,Cairo,2024-02-11,Yes,24,90,4.7,180

01.  Find students who need follow-up: not completed or score 
below 60.
02.  Handle missing ratings using a simple fair rule.
03.  Create a Progress Level idea based on Score: Low, Good, 
Excellent.
04.  Summarize average score and completion count by Course.
05.  Build one final conclusion about the strongest course and one 
improvement action.

In [22]:
filter_student_need_follow = df[(df['Done']=='No')|(df['Score'] <= 60)]
filter_student_need_follow

,StudentID,Name,Course,Level,City,EnrollDate,Done,Hours,Score,Rating,Price,Is_Completed
1,202,Mariam,Excel,Beginner,Giza,2024-02-03,No,7,54,NaN,80,False
4,205,Salma,SQL,Inter,Mansoura,2024-02-07,No,9,61,3.8,100,False

In [23]:
df.isnull().sum()

StudentID       0
Name            0
Course          0
Level           0
City            0
EnrollDate      0
Done            0
Hours           0
Score           0
Rating          1
Price           0
Is_Completed    0
dtype: int64

In [24]:

df['Rating']=df['Rating'].fillna(df['Rating'].mean())
df

,StudentID,Name,Course,Level,City,EnrollDate,Done,Hours,Score,Rating,Price,Is_Completed
0,201,Adam,Python,Beginner,Cairo,2024-02-01,Yes,18,88,4.800000,120,True
1,202,Mariam,Excel,Beginner,Giza,2024-02-03,No,7,54,4.616667,80,False
2,203,Yara,Power BI,Inter,Alex,2024-02-04,Yes,15,91,4.900000,150,True
3,204,Omar,Python,Beginner,Cairo,2024-02-06,Yes,20,95,5.000000,120,True
4,205,Salma,SQL,Inter,Mansoura,2024-02-07,No,9,61,3.800000,100,False
5,206,Hady,Power BI,Inter,Alex,2024-02-10,Yes,14,84,4.500000,150,True
6,207,Nour,Python,Advanced,Cairo,2024-02-11,Yes,24,90,4.700000,180,True

In [25]:
df['progress_level']=''
for i in range(len(df)):
    if df.loc[i,'Score']>85:
        df.loc[i,'progress_level'] = 'Excellent'
    elif df.loc[i,'Score']<65:
        df.loc[i,'progress_level'] = 'Low'
    else:
        df.loc[i,'progress_level'] = 'Good'

df

,StudentID,Name,Course,Level,City,EnrollDate,Done,Hours,Score,Rating,Price,Is_Completed,progress_level
0,201,Adam,Python,Beginner,Cairo,2024-02-01,Yes,18,88,4.800000,120,True,Excellent
1,202,Mariam,Excel,Beginner,Giza,2024-02-03,No,7,54,4.616667,80,False,Low
2,203,Yara,Power BI,Inter,Alex,2024-02-04,Yes,15,91,4.900000,150,True,Excellent
3,204,Omar,Python,Beginner,Cairo,2024-02-06,Yes,20,95,5.000000,120,True,Excellent
4,205,Salma,SQL,Inter,Mansoura,2024-02-07,No,9,61,3.800000,100,False,Low
5,206,Hady,Power BI,Inter,Alex,2024-02-10,Yes,14,84,4.500000,150,True,Good
6,207,Nour,Python,Advanced,Cairo,2024-02-11,Yes,24,90,4.700000,180,True,Excellent

In [21]:
df['Is_Completed'] = df['Done'] == 'Yes'

summarize_df = df.groupby('Course').agg(
    Avg_Score=('Score', 'mean'), Completed_Count=('Is_Completed', 'sum')
)

summarize_df

          Avg_Score  Completed_Count
Course
Excel          54.0                0
Power BI       87.5                2
Python         91.0                3
SQL            61.0                0

In [27]:
best_course = summarize_df.idxmax()
best_course

Avg_Score          Python
Completed_Count    Python
dtype: str