In [2]:
import pandas as pd 
import numpy as np 

data = {
    'EmployeeID': [101, 102, 103, 104, 105, 106, 107],
    'Name': ['Ali', 'Sara', 'Mona', 'Omar', 'Nour', 'Hassan', 'Laila'],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'Finance', 'IT'],
    'City': ['Cairo', 'Alex', 'Cairo', 'Giza', 'Cairo', 'Alex', 'Giza'],
    'Salary': [
        12000,
        9000,
        15000,
        13000,
        9500,
        14000,
        np.nan,
    ],
    'ExperienceYears': [2, 5, 4, 6, 3, 7, 1],
    'PerformanceScore': [85, 78, 92, 88, 73, 90, 69],
    'TrainingHours': [12, 18, 20, 15, 10, 25, 8],
    'Remote': [True, False, True, False, True, False, True],  # تحويل Yes/No إلى Boolean
    'JoinDate': pd.to_datetime([
        '2022-01-15',
        '2020-03-10',
        '2021-07-01',
        '2019-11-20',
        '2023-02-05',
        '2018-08-12',
        '2024-01-10',
    ]),
}

df = pd.DataFrame(data)

01.  Inspect the dataset using the basic discovery functions.
02.  Identify which columns have missing values.
03.  Access Name, Department, Salary, and PerformanceScore 
only.
04.  Filter IT employees and then filter high performers with score 
85 or more.
05.  Filter employees in Cairo or Alexandria.

In [4]:
df.head(3)

,EmployeeID,Name,Department,City,Salary,ExperienceYears,PerformanceScore,TrainingHours,Remote,JoinDate
0,101,Ali,IT,Cairo,12000.0,2,85,12,True,2022-01-15
1,102,Sara,HR,Alex,9000.0,5,78,18,False,2020-03-10
2,103,Mona,IT,Cairo,15000.0,4,92,20,True,2021-07-01

In [5]:
df.tail(3)

,EmployeeID,Name,Department,City,Salary,ExperienceYears,PerformanceScore,TrainingHours,Remote,JoinDate
4,105,Nour,HR,Cairo,9500.0,3,73,10,True,2023-02-05
5,106,Hassan,Finance,Alex,14000.0,7,90,25,False,2018-08-12
6,107,Laila,IT,Giza,NaN,1,69,8,True,2024-01-10

In [9]:
df.describe()

,EmployeeID,Salary,ExperienceYears,PerformanceScore,TrainingHours,JoinDate
count,7.000000,6.000000,7.000000,7.000000,7.000000,7
mean,104.000000,12083.333333,4.000000,82.142857,15.428571,2021-05-02 13:42:51.428571
min,101.000000,9000.000000,1.000000,69.000000,8.000000,2018-08-12 00:00:00
25%,102.500000,10125.000000,2.500000,75.500000,11.000000,2020-01-14 12:00:00
50%,104.000000,12500.000000,4.000000,85.000000,15.000000,2021-07-01 00:00:00
75%,105.500000,13750.000000,5.500000,89.000000,19.000000,2022-07-27 00:00:00
max,107.000000,15000.000000,7.000000,92.000000,25.000000,2024-01-10 00:00:00
std,2.160247,2416.954006,2.160247,8.896227,5.996030,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeID        7 non-null      int64
 1   Name              7 non-null      str
 2   Department        7 non-null      str
 3   City              7 non-null      str
 4   Salary            6 non-null      float64
 5   ExperienceYears   7 non-null      int64
 6   PerformanceScore  7 non-null      int64
 7   TrainingHours     7 non-null      int64
 8   Remote            7 non-null      bool
 9   JoinDate          7 non-null      datetime64[us]
dtypes: bool(1), datetime64[us](1), float64(1), int64(4), str(3)
memory usage: 728.0 bytes

In [7]:
df.shape

(7, 10)

In [10]:
df.isnull().sum()

EmployeeID          0
Name                0
Department          0
City                0
Salary              1
ExperienceYears     0
PerformanceScore    0
TrainingHours       0
Remote              0
JoinDate            0
dtype: int64

In [20]:
col_acess = ['Name','Department','Salary','PerformanceScore']
df[col_acess].head()

   Name Department   Salary  PerformanceScore
0   Ali         IT  12000.0                85
1  Sara         HR   9000.0                78
2  Mona         IT  15000.0                92
3  Omar    Finance  13000.0                88
4  Nour         HR   9500.0                73

In [21]:
Filtered_IT = df[df['Department']=='IT']
Filtered_IT

,EmployeeID,Name,Department,City,Salary,ExperienceYears,PerformanceScore,TrainingHours,Remote,JoinDate
0,101,Ali,IT,Cairo,12000.0,2,85,12,True,2022-01-15
2,103,Mona,IT,Cairo,15000.0,4,92,20,True,2021-07-01
6,107,Laila,IT,Giza,NaN,1,69,8,True,2024-01-10

In [24]:
Filted_High_Performance = df[(df['Department']=='IT')&(df['PerformanceScore']>85)]
Filted_High_Performance

,EmployeeID,Name,Department,City,Salary,ExperienceYears,PerformanceScore,TrainingHours,Remote,JoinDate
2,103,Mona,IT,Cairo,15000.0,4,92,20,True,2021-07-01

In [26]:
Filter_Region = df[(df['City'] == 'Alex') | (df['City'] == 'Cairo')]
Filter_Region

,EmployeeID,Name,Department,City,Salary,ExperienceYears,PerformanceScore,TrainingHours,Remote,JoinDate
0,101,Ali,IT,Cairo,12000.0,2,85,12,True,2022-01-15
1,102,Sara,HR,Alex,9000.0,5,78,18,False,2020-03-10
2,103,Mona,IT,Cairo,15000.0,4,92,20,True,2021-07-01
4,105,Nour,HR,Cairo,9500.0,3,73,10,True,2023-02-05
5,106,Hassan,Finance,Alex,14000.0,7,90,25,False,2018-08-12

01.  Use exact row/column selection to display the first 4 employees 
with Name, Salary, and Score.
02.  Fill missing Salary using a suitable simple strategy.
03.  Create employee level idea: Junior, Mid, Senior based on 
experience.
04.  Summarize average Salary and average Score by Department.
05.  Write the HR recommendation: who deserves recognition and 
which group needs training

In [27]:
selected_cols = ['Name','Salary','PerformanceScore']
df[selected_cols].head(4)

   Name   Salary  PerformanceScore
0   Ali  12000.0                85
1  Sara   9000.0                78
2  Mona  15000.0                92
3  Omar  13000.0                88

In [29]:
df['Salary']=df['Salary'].fillna(df['Salary'].mean())
df['Salary'].isnull().sum()

np.int64(0)

In [30]:
filtered_exp_max = df['ExperienceYears'].max()
filtered_exp_min = df['ExperienceYears'].min()
filtered_exp_avg = df['ExperienceYears'].mean()

print("filtered_exp_max : \n",filtered_exp_max)
print("filtered_exp_min : \n",filtered_exp_min)
print("filtered_exp_avg : \n",filtered_exp_avg)

filtered_exp_max :
 7
filtered_exp_min :
 1
filtered_exp_avg :
 4.0

In [42]:
df['Employee Level']=''

for i in range(len(df)):
    if df.loc[i,'ExperienceYears']>4:
        df.loc[i,'Employee Level'] = 'Junior'
    elif df.loc[i,'ExperienceYears']==4:
        df.loc[i,'Employee Level'] = 'Mid'
    else:
        df.loc[i, 'Employee Level'] = 'Senior'

df.head(5)

,EmployeeID,Name,Department,City,Salary,ExperienceYears,PerformanceScore,TrainingHours,Remote,JoinDate,Employee Level
0,101,Ali,IT,Cairo,12000.0,2,85,12,True,2022-01-15,Senior
1,102,Sara,HR,Alex,9000.0,5,78,18,False,2020-03-10,Junior
2,103,Mona,IT,Cairo,15000.0,4,92,20,True,2021-07-01,Mid
3,104,Omar,Finance,Giza,13000.0,6,88,15,False,2019-11-20,Junior
4,105,Nour,HR,Cairo,9500.0,3,73,10,True,2023-02-05,Senior

In [41]:
summarize_cols = df.groupby('Department')[['Salary','PerformanceScore']].mean()
summarize_cols

                  Salary  PerformanceScore
Department
Finance     13500.000000              89.0
HR           9250.000000              75.5
IT          13027.777778              82.0

In [39]:
deserve_recognition = df[df['PerformanceScore']>85][['Name','Department','TrainingHours','PerformanceScore']]
deserve_recognition

     Name Department  TrainingHours  PerformanceScore
2    Mona         IT             20                92
3    Omar    Finance             15                88
5  Hassan    Finance             25                90

In [40]:
need_trainninghours = df[df['PerformanceScore']<85][['Name','Department','TrainingHours','PerformanceScore']]
need_trainninghours

    Name Department  TrainingHours  PerformanceScore
1   Sara         HR             18                78
4   Nour         HR             10                73
6  Laila         IT              8                69