In [5]:
import pandas as pd

df = pd.DataFrame({
    "OrderID": [301, 302, 303, 304, 305, 306, 307],
    "OrderDate": [
        "2024-03-01",
        "2024-03-01",
        "2024-03-02",
        "2024-03-02",
        "2024-03-03",
        "2024-03-03",
        "2024-03-04"
    ],
    "Meal": [
        "Burger",
        "Pizza",
        "Pasta",
        "Salad",
        "Burger",
        "Sushi",
        "Pizza"
    ],
    "Category": [
        "Fast Food",
        "Italian",
        "Italian",
        "Healthy",
        "Fast Food",
        "Asian",
        "Italian"
    ],
    "Channel": [
        "Delivery",
        "Dine-in",
        "Delivery",
        "Takeaway",
        "Dine-in",
        "Delivery",
        "Delivery"
    ],
    "Qty": [2, 1, 1, 2, 3, 1, 2],
    "Price": [8.5, 12, 10.5, 6, 8.5, 16, 12],
    "Rating": [4.6, 4.8, 4.1, 4.4, 4.7, 4.9, 4.3],
    "Minutes": [32, 0, 45, 12, 0, 38, 41],
    "Payment": [
        "App",
        "Card",
        "App",
        "Cash",
        "Card",
        "App",
        "App"
    ],
    "Branch": [
        "Nasr City",
        "Maadi",
        "Maadi",
        "Nasr City",
        "Heliopolis",
        "Zamalek",
        "Maadi"
    ]
})
df

,OrderID,OrderDate,Meal,Category,Channel,Qty,Price,Rating,Minutes,Payment,Branch
0,301,2024-03-01,Burger,Fast Food,Delivery,2,8.5,4.6,32,App,Nasr City
1,302,2024-03-01,Pizza,Italian,Dine-in,1,12.0,4.8,0,Card,Maadi
2,303,2024-03-02,Pasta,Italian,Delivery,1,10.5,4.1,45,App,Maadi
3,304,2024-03-02,Salad,Healthy,Takeaway,2,6.0,4.4,12,Cash,Nasr City
4,305,2024-03-03,Burger,Fast Food,Dine-in,3,8.5,4.7,0,Card,Heliopolis
5,306,2024-03-03,Sushi,Asian,Delivery,1,16.0,4.9,38,App,Zamalek
6,307,2024-03-04,Pizza,Italian,Delivery,2,12.0,4.3,41,App,Maadi

01.  Inspect the dataset and identify the main numeric columns.
02.  Access Meal, Category, Channel, Quantity, UnitPrice, and 
Rating.
03.  Filter delivery orders only.
04.  Filter orders with rating 4.5 or more.
05.  Filter high-value orders: Quantity is 2 or more and UnitPrice 
is above 10

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    7 non-null      int64
 1   OrderDate  7 non-null      str
 2   Meal       7 non-null      str
 3   Category   7 non-null      str
 4   Channel    7 non-null      str
 5   Qty        7 non-null      int64
 6   Price      7 non-null      float64
 7   Rating     7 non-null      float64
 8   Minutes    7 non-null      int64
 9   Payment    7 non-null      str
 10  Branch     7 non-null      str
dtypes: float64(2), int64(3), str(6)
memory usage: 1.0 KB

In [8]:
main_cols_numeric = ['OrderID','Qty','Price','Rating','Minutes']
df[main_cols_numeric]

   OrderID  Qty  Price  Rating  Minutes
0      301    2    8.5     4.6       32
1      302    1   12.0     4.8        0
2      303    1   10.5     4.1       45
3      304    2    6.0     4.4       12
4      305    3    8.5     4.7        0
5      306    1   16.0     4.9       38
6      307    2   12.0     4.3       41

In [10]:
acess_cols = ['Meal','Category','Qty','Price','Rating']
df[acess_cols]

     Meal   Category  Qty  Price  Rating
0  Burger  Fast Food    2    8.5     4.6
1   Pizza    Italian    1   12.0     4.8
2   Pasta    Italian    1   10.5     4.1
3   Salad    Healthy    2    6.0     4.4
4  Burger  Fast Food    3    8.5     4.7
5   Sushi      Asian    1   16.0     4.9
6   Pizza    Italian    2   12.0     4.3

In [11]:
filter_delivery = df.loc[df['Channel']=='Delivery']
filter_delivery

,OrderID,OrderDate,Meal,Category,Channel,Qty,Price,Rating,Minutes,Payment,Branch
0,301,2024-03-01,Burger,Fast Food,Delivery,2,8.5,4.6,32,App,Nasr City
2,303,2024-03-02,Pasta,Italian,Delivery,1,10.5,4.1,45,App,Maadi
5,306,2024-03-03,Sushi,Asian,Delivery,1,16.0,4.9,38,App,Zamalek
6,307,2024-03-04,Pizza,Italian,Delivery,2,12.0,4.3,41,App,Maadi

In [13]:
filter_order = df.loc[df['Rating']>= 4.5]
filter_order

,OrderID,OrderDate,Meal,Category,Channel,Qty,Price,Rating,Minutes,Payment,Branch
0,301,2024-03-01,Burger,Fast Food,Delivery,2,8.5,4.6,32,App,Nasr City
1,302,2024-03-01,Pizza,Italian,Dine-in,1,12.0,4.8,0,Card,Maadi
4,305,2024-03-03,Burger,Fast Food,Dine-in,3,8.5,4.7,0,Card,Heliopolis
5,306,2024-03-03,Sushi,Asian,Delivery,1,16.0,4.9,38,App,Zamalek

In [15]:
filter_high = df[(df['Qty']>=2)&(df['Price']>10)]
filter_high

,OrderID,OrderDate,Meal,Category,Channel,Qty,Price,Rating,Minutes,Payment,Branch
6,307,2024-03-04,Pizza,Italian,Delivery,2,12.0,4.3,41,App,Maadi

01.  Use exact selection to display the first 5 orders with Meal, 
Channel, and Rating.
02.  Create revenue idea: Quantity multiplied by UnitPrice.
03.  Summarize total revenue by Category and by Branch.
04.  Compare average rating by Channel.
05.  Write final restaurant advice: hero meal, best channel, and 
branch to watch.

In [16]:
selection_to_dis = df.groupby('Meal')[['Channel','Rating']]
selection_to_dis.head(5)

    Channel  Rating
0  Delivery     4.6
1   Dine-in     4.8
2  Delivery     4.1
3  Takeaway     4.4
4   Dine-in     4.7
5  Delivery     4.9
6  Delivery     4.3

In [18]:
df['revenue'] = df['Qty'] * df['Price']
df

,OrderID,OrderDate,Meal,Category,Channel,Qty,Price,Rating,Minutes,Payment,Branch,revenue
0,301,2024-03-01,Burger,Fast Food,Delivery,2,8.5,4.6,32,App,Nasr City,17.0
1,302,2024-03-01,Pizza,Italian,Dine-in,1,12.0,4.8,0,Card,Maadi,12.0
2,303,2024-03-02,Pasta,Italian,Delivery,1,10.5,4.1,45,App,Maadi,10.5
3,304,2024-03-02,Salad,Healthy,Takeaway,2,6.0,4.4,12,Cash,Nasr City,12.0
4,305,2024-03-03,Burger,Fast Food,Dine-in,3,8.5,4.7,0,Card,Heliopolis,25.5
5,306,2024-03-03,Sushi,Asian,Delivery,1,16.0,4.9,38,App,Zamalek,16.0
6,307,2024-03-04,Pizza,Italian,Delivery,2,12.0,4.3,41,App,Maadi,24.0

In [21]:
total_total_revenue = df.groupby('revenue')[['Category','Branch']].sum()
total_total_revenue

               Category          Branch
revenue
10.5            Italian           Maadi
12.0     ItalianHealthy  MaadiNasr City
16.0              Asian         Zamalek
17.0          Fast Food       Nasr City
24.0            Italian           Maadi
25.5          Fast Food      Heliopolis

In [27]:
compare_avg = df.groupby('Channel')['Rating'].mean()
compare_avg

Channel
Delivery    4.475
Dine-in     4.750
Takeaway    4.400
Name: Rating, dtype: float64

In [30]:
hero_meal = selection_to_dis.idxmax()
hero_meal

        Channel  Rating
Meal
Burger        4       4
Pasta         2       2
Pizza         1       1
Salad         3       3
Sushi         5       5

In [31]:
best_channel = compare_avg.idxmax()
best_channel

'Dine-in'

In [33]:
best_branch = df.groupby("Branch")["revenue"].sum()

print(best_branch)

Branch
Heliopolis    25.5
Maadi         46.5
Nasr City     29.0
Zamalek       16.0
Name: revenue, dtype: float64

In [34]:
best_branch_to_watch = best_branch.idxmax()
best_branch_to_watch

'Maadi'