1. Show the first records and last records to understand the table.
2. Check rows, columns, column names, data types, and missing values.
3. Summarize the numeric columns: price, quantity, discount, and profit.
4. Select only Product, Category, UnitPrice, Quantity, and Profit for a quick product view.
5. Filter orders where Quantity is greater than 2

In [36]:
import pandas as pd 
import numpy as np

In [37]:
data = {
    "OrderID": [1001, 1002, 1003, 1004, 1005, 1006, 1007],
    "OrderDate": pd.to_datetime([
        "2024-01-03", "2024-01-04", "2024-01-05", 
        "2024-01-07", "2024-01-09", "2024-01-10", "2024-01-12"
    ]),
    "Region": ["East", "West", "North", "South", "East", "West", "North"],
    "Product": ["Laptop", "Mouse", "Monitor", "Keyboard", "Headset", "Laptop", "Mouse Pad"],
    "Category": ["Electronics", "Accessories", "Electronics", "Accessories", "Audio", "Electronics", "Accessories"],
    "UnitPrice": [1200, 25, 280, 45, 80, 1150, 15],
    "Quantity": [1, 3, 2, 2, 1, 1, 4],
    "Discount": [0.05, 0.00, 0.10, 0.00, 0.15, 0.00, 0.00],  # قيم مئوية محسوبة كأرقام عشريّة
    "PaymentMethod": ["Card", "Cash", "Online", "Card", "Online", "Card", "Cash"],
    "Profit": [210, 18, 95, 28, 22, 190, 16]
}
df = pd.DataFrame(data)

In [38]:
df.head()

,OrderID,OrderDate,Region,Product,Category,UnitPrice,Quantity,Discount,PaymentMethod,Profit
0,1001,2024-01-03,East,Laptop,Electronics,1200,1,0.05,Card,210
1,1002,2024-01-04,West,Mouse,Accessories,25,3,0.00,Cash,18
2,1003,2024-01-05,North,Monitor,Electronics,280,2,0.10,Online,95
3,1004,2024-01-07,South,Keyboard,Accessories,45,2,0.00,Card,28
4,1005,2024-01-09,East,Headset,Audio,80,1,0.15,Online,22

In [39]:
df.tail()

,OrderID,OrderDate,Region,Product,Category,UnitPrice,Quantity,Discount,PaymentMethod,Profit
2,1003,2024-01-05,North,Monitor,Electronics,280,2,0.10,Online,95
3,1004,2024-01-07,South,Keyboard,Accessories,45,2,0.00,Card,28
4,1005,2024-01-09,East,Headset,Audio,80,1,0.15,Online,22
5,1006,2024-01-10,West,Laptop,Electronics,1150,1,0.00,Card,190
6,1007,2024-01-12,North,Mouse Pad,Accessories,15,4,0.00,Cash,16

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        7 non-null      int64
 1   OrderDate      7 non-null      datetime64[us]
 2   Region         7 non-null      str
 3   Product        7 non-null      str
 4   Category       7 non-null      str
 5   UnitPrice      7 non-null      int64
 6   Quantity       7 non-null      int64
 7   Discount       7 non-null      float64
 8   PaymentMethod  7 non-null      str
 9   Profit         7 non-null      int64
dtypes: datetime64[us](1), float64(1), int64(4), str(4)
memory usage: 874.0 bytes

In [41]:
df.isnull().sum()

OrderID          0
OrderDate        0
Region           0
Product          0
Category         0
UnitPrice        0
Quantity         0
Discount         0
PaymentMethod    0
Profit           0
dtype: int64

In [42]:
numerical_category = ['UnitPrice','Quantity','Discount','Profit']
summarize_numerical_category = df[numerical_category].describe()
summarize_numerical_category

         UnitPrice  Quantity  Discount      Profit
count     7.000000  7.000000  7.000000    7.000000
mean    399.285714  2.000000  0.042857   82.714286
std     537.613775  1.154701  0.060749   84.834573
min      15.000000  1.000000  0.000000   16.000000
25%      35.000000  1.000000  0.000000   20.000000
50%      80.000000  2.000000  0.000000   28.000000
75%     715.000000  2.500000  0.075000  142.500000
max    1200.000000  4.000000  0.150000  210.000000

In [43]:
product_view = ['Product','Category','UnitPrice','Quantity','Profit']
df[product_view].head()

    Product     Category  UnitPrice  Quantity  Profit
0    Laptop  Electronics       1200         1     210
1     Mouse  Accessories         25         3      18
2   Monitor  Electronics        280         2      95
3  Keyboard  Accessories         45         2      28
4   Headset        Audio         80         1      22

In [44]:
filtered_quantity = df[df['Quantity']>2]

filtered_quantity

,OrderID,OrderDate,Region,Product,Category,UnitPrice,Quantity,Discount,PaymentMethod,Profit
1,1002,2024-01-04,West,Mouse,Accessories,25,3,0.0,Cash,18
6,1007,2024-01-12,North,Mouse Pad,Accessories,15,4,0.0,Cash,16

01.  Filter Electronics orders with Profit greater than 100.
02.  Select exact rows and columns using label-based and 
position-based selection.
03.  Create business columns conceptually: Gross Sales, Net 
Sales, and Profit Margin.
04.  Summarize total sales and profit by Category and Region.
05.  Build a final insight: best category, strongest region, and one 
product to promote.

In [45]:
electronic_order = df[(df['Category']=='Electronics')&(df['Profit']>100)]
electronic_order

,OrderID,OrderDate,Region,Product,Category,UnitPrice,Quantity,Discount,PaymentMethod,Profit
0,1001,2024-01-03,East,Laptop,Electronics,1200,1,0.05,Card,210
5,1006,2024-01-10,West,Laptop,Electronics,1150,1,0.00,Card,190

In [46]:
label_based = df.loc[0:2,['Product','UnitPrice']]
label_based

   Product  UnitPrice
0   Laptop       1200
1    Mouse         25
2  Monitor        280

In [47]:
pos_label = df.iloc[0:2,[3,4]]
pos_label

  Product     Category
0  Laptop  Electronics
1   Mouse  Accessories

In [48]:
df['Gross Sales']=df['UnitPrice'] * df['Quantity']
df['DiscountAmount'] = df['Gross Sales'] * df['Discount']
df['NetSales'] = df['Gross Sales'] - df['DiscountAmount']
df['Profit Margin'] = (df['Profit']/df['UnitPrice'])*100

cols_to_show = ['OrderID', 'Product', 'Gross Sales', 'DiscountAmount', 'NetSales', 'Profit', 'Profit Margin']
print(df[cols_to_show])

   OrderID    Product  Gross Sales  DiscountAmount  NetSales  Profit  \
0     1001     Laptop         1200            60.0    1140.0     210
1     1002      Mouse           75             0.0      75.0      18
2     1003    Monitor          560            56.0     504.0      95
3     1004   Keyboard           90             0.0      90.0      28
4     1005    Headset           80            12.0      68.0      22
5     1006     Laptop         1150             0.0    1150.0     190
6     1007  Mouse Pad           60             0.0      60.0      16

   Profit Margin
0      17.500000
1      72.000000
2      33.928571
3      62.222222
4      27.500000
5      16.521739
6     106.666667

In [49]:
summarize_cat_region = df.groupby(['Category','Region'])[['NetSales','Profit']].sum()
summarize_cat_region.sort_values(by='Profit',ascending=False)

                    NetSales  Profit
Category    Region
Electronics East      1140.0     210
            West      1150.0     190
            North      504.0      95
Accessories South       90.0      28
Audio       East        68.0      22
Accessories West        75.0      18
            North       60.0      16

In [50]:
print("Best Category :\n",df.groupby('Category')['NetSales'].sum().sort_values(ascending = False))

Best Category :
 Category
Electronics    2794.0
Accessories     225.0
Audio            68.0
Name: NetSales, dtype: float64

In [51]:
print("Strongest Region :\n",df.groupby('Region')['NetSales'].sum().sort_values(ascending = False))

Strongest Region :
 Region
West     1225.0
East     1208.0
North     564.0
South      90.0
Name: NetSales, dtype: float64

In [52]:
print("One Product to promote based on Net Sales \n",df.groupby('Product')['NetSales'].sum().sort_values(ascending=False))

One Product to promote based on Net Sales
 Product
Laptop       2290.0
Monitor       504.0
Keyboard       90.0
Mouse          75.0
Headset        68.0
Mouse Pad      60.0
Name: NetSales, dtype: float64